### ISSUE TITLE
[question/feature request] Expand macros in coverage reports

### ISSUE THREAD

**Issue by chpio** [kennytm/cargo-kcov#11]
Hi,

my code consists pretty much of macros which makes the reports pointless. Is there an option (i looked at the help page & couldn't find anything) or some thing to enable macro expansions in the reports?

**Comment by kennytm** [comment]
kcov gets line information from the DWARF symbol, which only contains the line information where the macro is invoked. See https://github.com/rust-lang/rust/issues/39153. 

Maybe you could try build with the environment variable `RUSTFLAGS=-Zdebug-macros`, as mentioned in that comment, to see if the result is better?
