### ISSUE TITLE
Pass KCOV-ARGS to kcov --merge

### ISSUE THREAD

**Issue by malbarbo** [kennytm/cargo-kcov#2]
The value of the new option [`--unreachable`](https://github.com/SimonKagstrom/kcov/pull/176) of kcov must be the same for each run and for the merge, if the are different, the coverage for the merged output will be different.

The `KCOV-ARGS` is passed to `kcov` for each executable but it is not passed when `kcov --merge` is called, so if `--unreachable` is passed in `KCOV-ARGS` the merged results will diverge because `kcov --merge` is called without `--unreachable`.

**Comment by malbarbo** [comment]
I could write a patch but it will conflict with https://github.com/kennytm/cargo-kcov/pull/3

**Comment by kennytm** [comment]
Fixed in 0.3.0 (9ff6d65) (GitHub should be auto-closing it 😞)

**Comment by malbarbo** [comment]
That was fast! Thanks.
