### ISSUE TITLE
Cargo kcov broken on latest nightly [a04b88d19 2018-03-19]

### ISSUE THREAD

**Issue by Lakier15** [kennytm/cargo-kcov#25]
It seems cargo kcov is broken on latest nightly.

I have cargo kcov as part of my CI and it has always worked. On the latest nightly it seems to be broken.

```sh
cargo kcov --all -- --exclude-pattern=/.cargo,/usr/lib --verify
```

produces 

```text
error: Found argument '--all' which wasn't expected, or isn't valid in this context
	Did you mean to put '--all' after the subcommand 'kcov'?

USAGE:
    cargo <SUBCOMMAND>

For more information try --help
```

I even tried to do

```sh
cargo kcov -- --exclude-pattern=/.cargo,/usr/lib --verify
```

but also fails producing

```text
error: Found argument '--exclude-pattern=/.cargo,/usr/lib' which wasn't expected, or isn't valid in this context

USAGE:
    cargo <SUBCOMMAND>

For more information try --help
```
## Versions
- rustc 1.26.0-nightly (a04b88d19 2018-03-19)
- cargo 1.26.0-nightly (d6c3983fe 2018-03-16)
- cargo-kcov 0.4.2

**Comment by kennytm** [comment]
This is caused by a rust-lang/cargo#5208 which the fix will be deployed soon
