### ISSUE TITLE
cargo-kcov and CI != Travis

### ISSUE THREAD

**Issue by pJunger** [kennytm/cargo-kcov#42]
Hi,

`cargo-kcov` seems to assume that it's running on Travis CI if `--coveralls` is used.
`kcov` itselfs takes the Travis Job ID or a token - maybe something like that could be (optionally) exposed by `cargo-kcov` as well?

**Comment by kennytm** [comment]
You could define the `$TRAVIS_JOB_ID` env var, like:

```sh
TRAVIS_JOB_ID=«job_id» cargo kcov ...
```

**Comment by pJunger** [comment]
Thank you!
